# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Nathan Shearer\Documents\PyCharm Projects\Play-Rack\src\play_rack\ui\PlayerWindow.ui'
#
# Created: Wed Jan 20 00:16:31 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_PlayerWindow(object):
    def setupUi(self, PlayerWindow):
        PlayerWindow.setObjectName("PlayerWindow")
        PlayerWindow.resize(364, 335)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/assets/play_button.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PlayerWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(PlayerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.device_label = QtGui.QLabel(self.frame_3)
        self.device_label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.device_label.setFont(font)
        self.device_label.setStyleSheet("background-color: rgb(239, 210, 154);\n"
"")
        self.device_label.setAlignment(QtCore.Qt.AlignCenter)
        self.device_label.setObjectName("device_label")
        self.horizontalLayout_6.addWidget(self.device_label)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: rgb(76, 189, 9);\n"
"border: 3px solid black;\n"
"    border-style: outset;\n"
"    border-radius: 10px;")
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setStyleSheet("border: none;")
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.filename = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.filename.setFont(font)
        self.filename.setStyleSheet("")
        self.filename.setObjectName("filename")
        self.verticalLayout_3.addWidget(self.filename)
        self.title = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.verticalLayout_3.addWidget(self.title)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.time_pos = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setWeight(75)
        font.setBold(True)
        self.time_pos.setFont(font)
        self.time_pos.setObjectName("time_pos")
        self.horizontalLayout_5.addWidget(self.time_pos)
        self.time_of = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.time_of.setFont(font)
        self.time_of.setObjectName("time_of")
        self.horizontalLayout_5.addWidget(self.time_of)
        self.time_dur = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.time_dur.setFont(font)
        self.time_dur.setObjectName("time_dur")
        self.horizontalLayout_5.addWidget(self.time_dur)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setText("")
        self.label_10.setTextFormat(QtCore.Qt.RichText)
        self.label_10.setPixmap(QtGui.QPixmap(":/buttons/assets/button_icons/media-play-16.png"))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.fade_in_btn = QtGui.QPushButton(self.centralwidget)
        self.fade_in_btn.setEnabled(False)
        self.fade_in_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/buttons/assets/button_icons/fade_in_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fade_in_btn.setIcon(icon1)
        self.fade_in_btn.setObjectName("fade_in_btn")
        self.horizontalLayout.addWidget(self.fade_in_btn)
        self.stop_btn = QtGui.QPushButton(self.centralwidget)
        self.stop_btn.setEnabled(False)
        self.stop_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/buttons/assets/button_icons/media-stop-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_btn.setIcon(icon2)
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout.addWidget(self.stop_btn)
        self.play_btn = QtGui.QPushButton(self.centralwidget)
        self.play_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/buttons/assets/button_icons/media-play-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_btn.setIcon(icon3)
        self.play_btn.setObjectName("play_btn")
        self.horizontalLayout.addWidget(self.play_btn)
        self.fade_out_btn = QtGui.QPushButton(self.centralwidget)
        self.fade_out_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/buttons/assets/button_icons/fade_out_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fade_out_btn.setIcon(icon4)
        self.fade_out_btn.setObjectName("fade_out_btn")
        self.horizontalLayout.addWidget(self.fade_out_btn)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.eject_btn = QtGui.QPushButton(self.centralwidget)
        self.eject_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/buttons/assets/button_icons/eject-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eject_btn.setIcon(icon5)
        self.eject_btn.setObjectName("eject_btn")
        self.horizontalLayout.addWidget(self.eject_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pos_scroll = QtGui.QScrollBar(self.centralwidget)
        self.pos_scroll.setOrientation(QtCore.Qt.Horizontal)
        self.pos_scroll.setObjectName("pos_scroll")
        self.verticalLayout.addWidget(self.pos_scroll)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.vol_scroll = QtGui.QScrollBar(self.centralwidget)
        self.vol_scroll.setOrientation(QtCore.Qt.Vertical)
        self.vol_scroll.setObjectName("vol_scroll")
        self.horizontalLayout_7.addWidget(self.vol_scroll)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        PlayerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PlayerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 364, 21))
        self.menubar.setObjectName("menubar")
        PlayerWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(PlayerWindow)
        self.statusbar.setObjectName("statusbar")
        PlayerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PlayerWindow)
        QtCore.QMetaObject.connectSlotsByName(PlayerWindow)

    def retranslateUi(self, PlayerWindow):
        PlayerWindow.setWindowTitle(QtGui.QApplication.translate("PlayerWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.device_label.setText(QtGui.QApplication.translate("PlayerWindow", "Device Label", None, QtGui.QApplication.UnicodeUTF8))
        self.filename.setText(QtGui.QApplication.translate("PlayerWindow", "My Song.mp3", None, QtGui.QApplication.UnicodeUTF8))
        self.title.setText(QtGui.QApplication.translate("PlayerWindow", "To Thou Be the Glory", None, QtGui.QApplication.UnicodeUTF8))
        self.time_pos.setText(QtGui.QApplication.translate("PlayerWindow", "1:23", None, QtGui.QApplication.UnicodeUTF8))
        self.time_of.setText(QtGui.QApplication.translate("PlayerWindow", "of", None, QtGui.QApplication.UnicodeUTF8))
        self.time_dur.setText(QtGui.QApplication.translate("PlayerWindow", "3:20", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
